import {useEffect,useRef,useState} from 'react'
import {ArrowLeft,BookOpen,Upload,ChevronLeft,ChevronRight,Bookmark,PanelLeft,MessageCircle,Maximize,Highlighter,X} from 'lucide-react'
import {request,uploadBook,type Book,type Section,type Annotation,type Turn} from './api'
import {createNote} from '../notes/api'
import {useSessionStore} from '../store/session'
import {useAppStore} from '../store/appStore'
import './books.css'
import {ContinuousReader} from './ContinuousReader'

export function BooksTab({active}:{active:boolean}){
  const[books,setBooks]=useState<Book[]>([]),[opened,setOpened]=useState<Book|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all')
  const input=useRef<HTMLInputElement>(null)
  const reload=()=>request<Book[]>().then(setBooks).catch(e=>setError(e.message))
  useEffect(()=>{if(active)void reload()},[active])
  if(opened)return <Reader key={opened.id} initial={opened} onBack={()=>{setOpened(null);void reload()}}/>
  const reading=books.find(b=>b.position>1&&!b.finished)
  return <section className="books-library">
    <header><div><span className="books-eyebrow">YOUR READING SPACE</span><h1>Books</h1><p>Read at your own pace. Explore ideas with a companion.</p></div><button className="books-primary" disabled={busy} onClick={()=>input.current?.click()}><Upload size={16}/>{busy?'Extracting book…':'Upload books'}</button><input hidden ref={input} type="file" accept=".pdf,.epub" multiple onChange={async e=>{setBusy(true);setError('');try{for(const file of Array.from(e.target.files||[]))await uploadBook(file);await reload()}catch(err){setError((err as Error).message)}finally{setBusy(false);e.target.value=''}}}/></header>
    {error&&<p role="alert" className="books-error">{error}</p>}
    {reading&&<button className="books-resume" onClick={()=>setOpened(reading)}><BookOpen size={36}/><div><small>CONTINUE READING</small><h2>{reading.title}</h2><span>{reading.format==='pdf'?'Page':'Chapter'} {reading.position} of {reading.total} · {Math.round(reading.position/reading.total*100)}%</span></div><span>Resume →</span></button>}
    <div className="books-tools"><input aria-label="Search books" placeholder="Search your library…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter books" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All books</option><option value="new">New</option><option value="reading">Reading</option><option value="finished">Finished</option></select><span>{books.length} books · PDF / EPUB</span></div>
    {!books.length&&!busy&&<div className="books-empty"><BookOpen size={48}/><h2>A shelf for your next discovery</h2><p>Upload a PDF or EPUB. Your place, notes, and study conversations stay with the book.</p><button onClick={()=>input.current?.click()}>Add your first book</button></div>}
    <div className="books-grid">{books.filter(b=>(b.title+' '+b.author).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='finished'?b.finished:filter==='new'?b.position===1&&!b.finished:b.position>1&&!b.finished))).map((b,i)=><article className="books-tile" key={b.id}><button className={`books-cover cover-${i%5}`} onClick={()=>setOpened(b)}><span>{b.format.toUpperCase()}</span><BookOpen size={30}/><strong>{b.title}</strong><small>{b.author||'Your library'}</small></button><h3>{b.title}</h3><p>{b.author||'Unknown author'}</p><progress max={b.total} value={b.position}/><div><span>{b.status==='needs_ocr'?'OCR needed for AI':b.finished?'Finished':`${b.position} / ${b.total}`}</span><button onClick={()=>{if(window.confirm(`Remove “${b.title}” and its reading notes?`))void request(`/${b.id}`,'DELETE').then(reload).catch(e=>setError(e.message))}}>Remove</button></div></article>)}</div>
  </section>
}

function Reader({initial,onBack}:{initial:Book;onBack:()=>void}){
  const[b,setBook]=useState(initial),[page,setPage]=useState(initial.position),[section,setSection]=useState<Section|null>(null),[toc,setToc]=useState<Section[]>([]),[annotations,setAnnotations]=useState<Annotation[]>([]),[turns,setTurns]=useState<Turn[]>([])
  const[theme,setTheme]=useState(String(initial.preferences.theme||'sepia')),[font,setFont]=useState(Number(initial.preferences.font||19)),[original,setOriginal]=useState(initial.status==='needs_ocr'),[left,setLeft]=useState(false),[right,setRight]=useState(()=>window.matchMedia('(min-width: 701px)').matches),[focus,setFocus]=useState(false)
  const[selection,setSelection]=useState(''),[scope,setScope]=useState('current'),[start,setStart]=useState(initial.position),[end,setEnd]=useState(initial.position),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('Saved'),[spoilers,setSpoilers]=useState(true),[search,setSearch]=useState(''),[results,setResults]=useState<(Section&{excerpt:string})[]>([]),[citation,setCitation]=useState('')
  const reader=useRef<HTMLDivElement>(null),saveTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),loadVersion=useRef(0)
  const[goal,setGoal]=useState(String(initial.preferences.goal||'Understand the main ideas')),[minutes,setMinutes]=useState(Number(initial.preferences.minutes||20))
  const [reading_mode,setReadingMode]=useState(initial.preferences.reading_mode==='scroll'?'scroll':'pages')
  const [scroll_target,setScrollTarget]=useState({number:initial.position,offset:initial.offset,revision:0})
  const currentOffset=useRef(initial.offset)
  const saveQueue=useRef(Promise.resolve())
  const unit=b.format==='pdf'?'Page':'Chapter'
  useEffect(()=>()=>{if('speechSynthesis' in window)speechSynthesis.cancel()},[])
  const base=`/${b.id}`
  const refreshAnnotations=()=>request<Annotation[]>(`${base}/annotations`).then(setAnnotations)
  useEffect(()=>{void request<Section[]>(`${base}/contents`).then(setToc).catch(e=>setError(e.message));void refreshAnnotations();void request<Turn[]>(`${base}/messages`).then(setTurns).catch(e=>setError(e.message))},[b.id])
  useEffect(()=>{const version=++loadVersion.current;if(reading_mode==='scroll'&&!original)return;setSection(null);setSelection('');void request<Section>(`${base}/sections/${page}`).then(s=>{if(version!==loadVersion.current)return;setSection(s);requestAnimationFrame(()=>{if(reader.current)reader.current.scrollTop=page===initial.position?initial.offset*(reader.current.scrollHeight-reader.current.clientHeight):0})}).catch(e=>setError(e.message))},[page,b.id,reading_mode,original])
  useEffect(()=>()=>clearTimeout(saveTimer.current),[])
  const persist=(position=page,offset=0,finished=Boolean(b.finished))=>{setSaved('Saving…');const payload={position,offset,finished,preferences:{theme,font,goal,minutes,reading_mode}};saveQueue.current=saveQueue.current.then(()=>request<Book>(`${base}/progress`,'PUT',payload)).then(next=>{setBook(next);setSaved('Saved')}).catch(e=>{setSaved('Not saved');setError(e.message)});return saveQueue.current}
  useEffect(()=>{const timer=setTimeout(()=>{const el=reader.current;void persist(page,reading_mode==='scroll'&&!original?currentOffset.current:el&&el.scrollHeight>el.clientHeight?el.scrollTop/(el.scrollHeight-el.clientHeight):0)},500);return()=>clearTimeout(timer)},[theme,font,goal,minutes,page,reading_mode])
  const go=(n:number)=>{if(!Number.isInteger(n)||n<1||n>b.total)return;clearTimeout(saveTimer.current);currentOffset.current=0;setScrollTarget(t=>({number:n,offset:0,revision:t.revision+1}));setPage(n);setStart(n);setEnd(n);void persist(n)}
  const annotate=async(kind:string)=>{const note=kind==='note'?window.prompt('Your reading note',''):'';if(note===null)return;try{await request(`${base}/annotations`,'POST',{section:page,kind,quote:selection,note,color:'amber'});await refreshAnnotations();setSelection('')}catch(e){setError((e as Error).message)}}
  const ask=async(action='ask')=>{setBusy(true);setError('');const a=scope==='book'?1:scope==='range'?start:page;const z=scope==='book'?b.total:scope==='range'?end:page;try{const result=await request<Turn>(`${base}/ask`,'POST',{question:action==='guide'?`Goal: ${goal}. Available reading time: ${minutes} minutes. ${question}`:question,start:a,end:z,selection:scope==='selection'?selection:'',action,avoid_spoilers:spoilers});setTurns(t=>[...t,result]);setQuestion('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const chat=(instruction:string,first=page,last=page)=>{useSessionStore.getState().setPendingChatInput(`${instruction}\n@book:${b.id}:pages:${first}-${last}`);useAppStore.getState().setActiveTab('chat')}
  const exportNote=async(content:string)=>{try{await createNote(`${b.title.slice(0,65)} - reading ${Date.now()}`,content);setSaved('Saved to Notes')}catch(e){setError((e as Error).message)}}
  return <section className={`book-reader ${focus?'book-focus':''}`} data-paper={theme}>
    <header className="reader-header"><button onClick={()=>{const el=reader.current;void persist(page,reading_mode==='scroll'&&!original?currentOffset.current:el&&el.scrollHeight>el.clientHeight?el.scrollTop/(el.scrollHeight-el.clientHeight):0).then(onBack)}}><ArrowLeft size={16}/>Library</button><div><strong>{b.title}</strong><small>{b.author}</small></div><button aria-label="Toggle contents" onClick={()=>setLeft(!left)}><PanelLeft size={17}/></button><select aria-label="Reader theme" value={theme} onChange={e=>setTheme(e.target.value)}><option value="paper">Paper</option><option value="sepia">Sepia</option><option value="dark">Dark</option></select><select aria-label="Text size" value={font} onChange={e=>setFont(Number(e.target.value))}>{[16,19,22,26,30].map(x=><option key={x} value={x}>{x}px</option>)}</select>{b.format==='pdf'&&<button onClick={()=>{setScrollTarget(t=>({number:page,offset:currentOffset.current,revision:t.revision+1}));setOriginal(!original)}}>{original?'Text view':'Original PDF'}</button>}<button className="reading-assistant-toggle" aria-label={right?"Close reading assistant":"Open reading assistant"} aria-expanded={right} aria-controls="book-reading-assistant" onClick={()=>setRight(!right)}><MessageCircle size={17}/><span>{right?"Hide AI assistant":"Open AI assistant"}</span></button><button aria-label="Focus mode" onClick={()=>setFocus(!focus)}><Maximize size={17}/></button></header>
    {error&&<div className="books-error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
    <div className="reader-layout">
      <details className="reading-plan"><summary>Reading goal & exports</summary><label>Goal<input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Understand the main ideas"/></label><label>Minutes<input type="number" min={5} max={120} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><button onClick={()=>void persist(page,b.offset)}>Save preferences</button><button onClick={()=>void request(`${base}/artifact`,'POST').then(()=>setSaved('Exported to Artifacts')).catch(e=>setError(e.message))}>Export to Artifacts</button><a href={`/api/books${base}/export`}>Download journal</a></details>
      {left&&<aside className="reader-contents"><header><strong>Explore this book</strong><button onClick={()=>setLeft(false)}><X size={14}/></button></header><form onSubmit={e=>{e.preventDefault();void request<(Section&{excerpt:string})[]>(`${base}/search?q=${encodeURIComponent(search)}`).then(setResults).catch(e=>setError(e.message))}}><input placeholder="Search in book…" value={search} onChange={e=>setSearch(e.target.value)}/><button>Search</button></form>{results.map(r=><button key={r.number} onClick={()=>go(r.number)}>{r.title}<small>{r.excerpt}</small></button>)}<details open><summary>Contents · {toc.length} {unit.toLowerCase()}s</summary>{toc.map(s=><button key={s.number} aria-current={page===s.number?'page':undefined} onClick={()=>go(s.number)}>{s.number}. {s.title}</button>)}</details><details open><summary>Bookmarks & notes</summary>{annotations.map(a=><div className="reading-annotation" key={a.id}><button onClick={()=>go(a.section)}>{unit} {a.section} · {a.kind}<small>{a.quote||a.note||'Bookmark'}</small></button><button aria-label="Delete annotation" onClick={()=>void request(`${base}/annotations/${a.id}`,'DELETE').then(refreshAnnotations)}>×</button></div>)}</details><a href={`/api/books${base}/export`} download>Export reading journal</a></aside>}
      <div className="reading-main"><div className="reading-mode-bar"><div className="reading-mode-switch" role="group" aria-label="Reading mode" data-mode={reading_mode}><span className="reading-mode-glider" aria-hidden="true"/>{(['pages','scroll'] as const).map(mode=><button key={mode} aria-pressed={!original&&reading_mode===mode} onClick={()=>{clearTimeout(saveTimer.current);currentOffset.current=0;setSelection('');setScrollTarget(t=>({number:page,offset:0,revision:t.revision+1}));setReadingMode(mode);setOriginal(false)}}>{mode==='pages'?'Pages':'Vertical scroll'}</button>)}</div>{original&&<small>Original PDF · use viewer controls</small>}</div><div className="reading-actions"><span>{unit} {page} of {b.total}{section&&section.label!==String(page)?` · printed ${section.label}`:''}</span><button onClick={()=>void annotate('bookmark')}><Bookmark size={14}/>Bookmark</button><button onClick={()=>void annotate('note')}>Add note</button></div>
        {selection&&<div className="reading-selection"><span>{selection.length} characters selected</span><button onClick={()=>void annotate('highlight')}><Highlighter size={14}/>Highlight</button><button onClick={()=>{setScope('selection');setRight(true)}}>Ask about selection</button><button onClick={()=>setSelection('')}>×</button></div>}
        {citation&&<div className="reading-citation"><button onClick={()=>setCitation('')}>×</button><strong>Cited passage</strong><p>{citation}</p></div>}
        {original&&b.format==='pdf'?<iframe className="reading-pdf" key={page} title="Original book PDF" src={`/api/books${base}/original#page=${page}&view=FitH`}/>:reading_mode==='scroll'?<ContinuousReader book_id={b.id} title={b.title} total={b.total} unit={unit} font={font} target={scroll_target} annotations={annotations} onPosition={(s,offset)=>{if(s.number!==page)setSelection('');currentOffset.current=offset;setPage(s.number);setSection(s);clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>void persist(s.number,offset),700)}} onSelection={(text,s)=>{setSelection(text);setPage(s.number);setSection(s);setStart(s.number);setEnd(s.number)}}/>:<div className="reading-scroll" ref={reader} onScroll={()=>{clearTimeout(saveTimer.current);const el=reader.current;if(!el)return;const offset=el.scrollHeight>el.clientHeight?el.scrollTop/(el.scrollHeight-el.clientHeight):0;saveTimer.current=setTimeout(()=>void persist(page,offset),700)}} onPointerUp={()=>{const selected=window.getSelection();if(selected?.anchorNode&&reader.current?.contains(selected.anchorNode)&&selected.focusNode&&reader.current.contains(selected.focusNode))setSelection(selected.toString().slice(0,10000))}}><article className="reading-page" style={{fontSize:font}}><small>{b.title} / {unit} {page}</small><h2>{b.format==='pdf'?(section?.title||'Loading…'):''}</h2>{section?.text?section.text.split(/\n\s*\n/).map((paragraph,i)=><p key={i}>{annotations.some(a=>a.section===page&&a.kind==='highlight'&&paragraph.includes(a.quote)&&a.quote)?<Highlighted paragraph={paragraph} quotes={annotations.filter(a=>a.section===page&&a.kind==='highlight').map(a=>a.quote)}/>:paragraph}</p>):section&&<p>No extractable text on this page. Open Original PDF to read it; AI requires OCR for scanned pages.</p>}</article></div>}
        <footer className="reader-footer"><button disabled={page===1} onClick={()=>go(page-1)}><ChevronLeft size={16}/>Previous</button><label>{unit}<input aria-label="Reading location" type="number" min={1} max={b.total} value={page} onChange={e=>go(Number(e.target.value))}/>/ {b.total}</label><small>{saved}</small><button onClick={()=>void persist(page,0,!b.finished)}>{b.finished?'Mark reading':'Mark finished'}</button><button disabled={page===b.total} onClick={()=>go(page+1)}>Next<ChevronRight size={16}/></button></footer>
      </div>
      {right&&<aside className="reading-assistant" id="book-reading-assistant"><header><div><span className="books-eyebrow">READING COMPANION</span><h3>Think it through</h3></div><button aria-label="Close reading assistant panel" onClick={()=>setRight(false)}><X size={16}/></button></header><label>Use sources from<select value={scope} onChange={e=>setScope(e.target.value)}><option value="current">Current {unit.toLowerCase()}</option><option value="range">{unit} range</option><option value="book">Entire book</option><option value="selection" disabled={!selection}>Selected text</option></select></label>{scope==='range'&&<div className="reading-range"><input aria-label="First location" type="number" min={1} max={b.total} value={start} onChange={e=>setStart(Number(e.target.value))}/><span>to</span><input aria-label="Last location" type="number" min={start} max={b.total} value={end} onChange={e=>setEnd(Number(e.target.value))}/></div>}<label className="reading-spoilers"><input type="checkbox" checked={spoilers} onChange={e=>setSpoilers(e.target.checked)}/>Avoid spoilers after {unit.toLowerCase()} {b.position}</label><div className="reading-ai-actions">{[['guide','Read with me'],['explain','Explain'],['summarize','Summarize'],['quiz','Quiz me'],['flashcards','Flashcards'],['connect','Connect ideas']].map(([action,title])=><button key={action} disabled={busy} onClick={()=>void ask(action)}>{title}</button>)}</div>
        <div className="reading-turns">{!turns.length&&<p className="reading-hint">Select a passage or range, then ask a question. Answers use excerpts from your book. Long ranges may be sampled.</p>}{turns.map(t=><article className="reading-turn" key={t.id}><small>{unit}s {t.scope.start}–{t.scope.end} · {t.scope.action}</small><strong>{t.question}</strong><div>{t.answer.split(/(\[S\d+\])/).map((part,i)=>{const c=t.citations.find(c=>`[${c.id}]`===part);return c?<button className="reading-source" key={i} title={c.excerpt} onClick={()=>{go(c.number);setCitation(c.excerpt)}}>{part}</button>:<span key={i}>{part}</span>})}</div><div className="reading-turn-tools"><button onClick={()=>{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t.answer.replace(/\[S\d+\]/g,'')))}}>Listen</button><button onClick={()=>speechSynthesis.cancel()}>Stop audio</button><button onClick={()=>void exportNote(`${t.question}\n\n${t.answer}\n\n@book:${JSON.stringify(b.title)}:pages:${t.scope.start}-${t.scope.end}`)}>Save to Notes</button><button onClick={()=>chat(`Continue this reading discussion: ${t.question}\n${t.answer}`,t.scope.start,t.scope.end)}>Continue in chat</button></div></article>)}{busy&&<p role="status">Reading your sources…</p>}</div><form className="reading-question" onSubmit={e=>{e.preventDefault();void ask()}}><textarea aria-label="Ask reading assistant" placeholder="Ask about this passage, or answer the quiz…" value={question} onChange={e=>setQuestion(e.target.value)} rows={3}/><button className="books-primary" disabled={busy||!question.trim()}>Ask sources</button></form><button className="reading-map" onClick={()=>chat('Create a concept map from this reading. Ask which existing Whiteboard canvas to use, or create a new one if requested.')}>Create Whiteboard concept map ↗</button>
      </aside>}
    </div>
  </section>
}

function Highlighted({paragraph,quotes}:{paragraph:string;quotes:string[]}){const quote=quotes.find(q=>q&&paragraph.includes(q));if(!quote)return <>{paragraph}</>;const at=paragraph.indexOf(quote);return <>{paragraph.slice(0,at)}<mark>{quote}</mark>{paragraph.slice(at+quote.length)}</>}
