"""OpenAI Codex model catalog.

These models use the Responses API (/v1/responses), not Chat Completions.

Source: https://platform.openai.com/docs/models
"""

from __future__ import annotations

from .base import ModelInfo

MODELS: list[ModelInfo] = [
    ModelInfo(
        id="gpt-5.3-codex",
        context_window=200_000,
        max_output=100_000,
        input_price=2.50,
        output_price=10.00,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=False,
        capability_tier="frontier",
        latency_tier="medium",
        knowledge_cutoff="2025-06",
        recommended_tasks=("code generation", "code editing", "refactoring", "debugging"),
        fallback_models=("gpt-5.2-codex", "gpt-5.1-codex"),
        quality_rank=1,
        cost_efficiency_rank=4,
        description="GPT-5.3 Codex — latest, strongest coding model (Responses API).",
    ),
    ModelInfo(
        id="gpt-5.2-codex",
        context_window=200_000,
        max_output=100_000,
        input_price=2.00,
        output_price=8.00,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=False,
        capability_tier="advanced",
        latency_tier="medium",
        knowledge_cutoff="2025-06",
        recommended_tasks=("code generation", "code editing", "refactoring", "debugging"),
        fallback_models=("gpt-5.1-codex", "gpt-5-codex"),
        quality_rank=2,
        cost_efficiency_rank=3,
        description="GPT-5.2 Codex — high quality coding model (Responses API).",
    ),
    ModelInfo(
        id="gpt-5.1-codex",
        context_window=200_000,
        max_output=100_000,
        input_price=1.50,
        output_price=6.00,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=False,
        capability_tier="advanced",
        latency_tier="fast",
        knowledge_cutoff="2025-03",
        recommended_tasks=("code generation", "code editing", "refactoring", "test writing"),
        fallback_models=("gpt-5-codex", "gpt-5.1-codex-mini"),
        quality_rank=3,
        cost_efficiency_rank=2,
        description="GPT-5.1 Codex — balanced coding model (Responses API).",
    ),
    ModelInfo(
        id="gpt-5.1-codex-mini",
        context_window=200_000,
        max_output=100_000,
        input_price=0.50,
        output_price=2.00,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=False,
        capability_tier="efficient",
        latency_tier="fast",
        knowledge_cutoff="2025-03",
        recommended_tasks=("code completion", "simple edits", "test writing", "quick fixes"),
        fallback_models=("gpt-5-codex",),
        quality_rank=5,
        cost_efficiency_rank=1,
        description="GPT-5.1 Codex Mini — fast, cheap coding model (Responses API).",
    ),
    ModelInfo(
        id="gpt-5.1-codex-max",
        context_window=200_000,
        max_output=100_000,
        input_price=10.00,
        output_price=40.00,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=False,
        capability_tier="frontier",
        latency_tier="slow",
        knowledge_cutoff="2025-03",
        recommended_tasks=("complex refactoring", "architecture", "hard debugging"),
        fallback_models=("gpt-5.1-codex",),
        quality_rank=1,
        cost_efficiency_rank=6,
        description="GPT-5.1 Codex Max — maximum compute coding model (Responses API).",
    ),
    ModelInfo(
        id="gpt-5-codex",
        context_window=200_000,
        max_output=100_000,
        input_price=1.25,
        output_price=5.00,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=False,
        capability_tier="advanced",
        latency_tier="fast",
        knowledge_cutoff="2025-03",
        recommended_tasks=("code generation", "code editing", "refactoring"),
        fallback_models=("gpt-5.1-codex-mini",),
        quality_rank=4,
        cost_efficiency_rank=2,
        description="GPT-5 Codex — original GPT-5 coding model (Responses API).",
    ),
]
