"""Google Gemini model catalog.

Source: https://ai.google.dev/gemini-api/docs/models
         https://ai.google.dev/pricing
"""

from __future__ import annotations

from .base import ModelInfo

MODELS: list[ModelInfo] = [
    ModelInfo(
        id="gemini-3-flash-preview",
        context_window=1_000_000,
        max_output=65_536,
        input_price=0.5,
        output_price=3,
        pricing_source='https://ai.google.dev/gemini-api/docs/pricing',
        pricing_verified_at='2026-09-09',
        pricing_notes='Standard paid-tier text input/output. Pro rates shown for prompts up to 200K tokens. Audio, cache storage and grounding billed separately.',
        cached_input_price=0.05,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 3 Flash Preview — next-gen reasoning with thinking",
        capability_tier="frontier",
        latency_tier="fast",
    ),
    ModelInfo(
        id="gemini-3-pro-preview",
        context_window=1_000_000,
        max_output=65_536,
        input_price=1.25,
        output_price=10.0,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 3 Pro Preview — frontier reasoning, large context",
        capability_tier="frontier",
        latency_tier="medium",
    ),
    ModelInfo(
        id="gemini-2.5-pro",
        long_context_input_price=2.50,
        long_context_output_price=15.0,
        context_window=2_000_000,
        max_output=8_192,
        input_price=1.25,
        output_price=10,
        pricing_source='https://ai.google.dev/gemini-api/docs/pricing',
        pricing_verified_at='2026-09-09',
        pricing_notes='Standard paid-tier text input/output. Pro rates shown for prompts up to 200K tokens. Audio, cache storage and grounding billed separately.',
        cached_input_price=0.125,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 2.5 Pro — frontier reasoning, 2M context",
        capability_tier="frontier",
        latency_tier="medium",
    ),
    ModelInfo(
        id="gemini-2.5-flash",
        context_window=1_000_000,
        max_output=8_192,
        input_price=0.3,
        output_price=2.5,
        pricing_source='https://ai.google.dev/gemini-api/docs/pricing',
        pricing_verified_at='2026-09-09',
        pricing_notes='Standard paid-tier text input/output. Pro rates shown for prompts up to 200K tokens. Audio, cache storage and grounding billed separately.',
        cached_input_price=0.03,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 2.5 Flash — fast, cheap, 1M context",
        capability_tier="efficient",
        latency_tier="fast",
    ),
    ModelInfo(
        id="gemini-2.5-flash-lite",
        context_window=1_000_000,
        max_output=8_192,
        input_price=0.1,
        output_price=0.4,
        pricing_source='https://ai.google.dev/gemini-api/docs/pricing',
        pricing_verified_at='2026-09-09',
        pricing_notes='Standard paid-tier text input/output. Pro rates shown for prompts up to 200K tokens. Audio, cache storage and grounding billed separately.',
        cached_input_price=0.01,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 2.5 Flash-Lite — cheapest Gemini tier",
        capability_tier="lightweight",
        latency_tier="very_fast",
    ),
    ModelInfo(
        id="gemini-2.0-flash",
        context_window=1_000_000,
        max_output=8_192,
        input_price=0.10,
        output_price=0.40,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 2.0 Flash (previous gen)",
        capability_tier="efficient",
        latency_tier="very_fast",
    ),
    ModelInfo(
        id="gemini-1.5-pro",
        context_window=2_000_000,
        max_output=8_192,
        input_price=1.25,
        output_price=5.0,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 1.5 Pro (legacy)",
        capability_tier="advanced",
        latency_tier="medium",
    ),
    ModelInfo(
        id="gemini-1.5-flash",
        context_window=1_000_000,
        max_output=8_192,
        input_price=0.075,
        output_price=0.30,
        supports_tools=True,
        supports_vision=True,
        description="Gemini 1.5 Flash (legacy)",
        capability_tier="efficient",
        latency_tier="very_fast",
    ),
]
