"""OpenAI GPT model catalog.

Source: https://developers.openai.com/api/docs/models
         https://developers.openai.com/api/docs/pricing
"""

from __future__ import annotations

from .base import ModelInfo

# ── Current models (with full routing metadata) ──────────────────────────────

MODELS: list[ModelInfo] = [
    ModelInfo(
        id="gpt-6-astra",
        context_window=1_050_000,
        max_output=128_000,
        input_price=10.0,
        output_price=50.0,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="frontier",
        latency_tier="slow",
        knowledge_cutoff="2026-04",
        recommended_tasks=("complex reasoning", "advanced coding", "agent planning", "multimodal analysis"),
        fallback_models=("gpt-5.6-terra", "gpt-5.6-sol"),
        quality_rank=1,
        cost_efficiency_rank=6,
        description="Most capable GPT model — frontier reasoning, agentic coding, multimodal.",
    ),
    ModelInfo(
        id="gpt-5.6-terra",
        context_window=1_050_000,
        max_output=128_000,
        input_price=2.0,
        output_price=12.0,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="advanced",
        latency_tier="medium",
        knowledge_cutoff="2026-02",
        recommended_tasks=("coding", "analysis", "agent pipelines", "data transformation"),
        fallback_models=("gpt-5.6-luna", "gpt-5.6-sol"),
        quality_rank=2,
        cost_efficiency_rank=4,
        description="Balanced reasoning + tool use (mini tier).",
    ),
    ModelInfo(
        id="gpt-5.6-luna",
        context_window=1_050_000,
        max_output=128_000,
        input_price=0.20,
        output_price=1.20,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="lightweight",
        latency_tier="very_fast",
        knowledge_cutoff="2026-02",
        recommended_tasks=("classification", "routing", "intent detection", "cheap chat"),
        fallback_models=("gpt-5.4-nano",),
        quality_rank=5,
        cost_efficiency_rank=1,
        description="Fast, cheap general model (nano tier).",
    ),
    ModelInfo(
        id="gpt-5.6-sol",
        context_window=1_050_000,
        max_output=128_000,
        input_price=4.0,
        output_price=16.0,
        supports_tools=True,
        supports_vision=True,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="advanced",
        latency_tier="medium",
        knowledge_cutoff="2026-02",
        recommended_tasks=("multimodal reasoning", "vision tasks", "agentic coding"),
        fallback_models=("gpt-5.6-terra", "gpt-5.6-luna"),
        quality_rank=4,
        cost_efficiency_rank=3,
        description="Cheapest full multimodal reasoning model with tool calling (output price estimated).",
    ),
    # ── Previous generation ───────────────────────────────────────────────────
    ModelInfo(
        id="gpt-5.4",
        context_window=1_050_000,
        max_output=128_000,
        input_price=2.50,
        output_price=15.0,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="frontier",
        latency_tier="medium",
        max_rpm=500,
        max_tpm=2_000_000,
        knowledge_cutoff="2025-12",
        recommended_tasks=("complex reasoning", "advanced coding", "agent planning", "long context analysis"),
        fallback_models=("gpt-5.2", "gpt-5.1"),
        quality_rank=1,
        cost_efficiency_rank=6,
        description="GPT-5.4 flagship (previous gen).",
    ),
    ModelInfo(
        id="gpt-5.4-mini",
        context_window=400_000,
        max_output=128_000,
        input_price=0.75,
        output_price=4.50,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="efficient",
        latency_tier="fast",
        knowledge_cutoff="2025-12",
        recommended_tasks=("classification", "intent detection", "routing", "cheap chat inference"),
        fallback_models=("gpt-5.4-nano",),
        quality_rank=5,
        cost_efficiency_rank=2,
        description="GPT-5.4 mini tier (previous gen; output price estimated).",
    ),
    ModelInfo(
        id="gpt-5.4-nano",
        context_window=400_000,
        max_output=128_000,
        input_price=0.20,
        output_price=1.20,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="lightweight",
        latency_tier="very_fast",
        knowledge_cutoff="2025-12",
        recommended_tasks=("intent detection", "classification", "LLM router"),
        fallback_models=(),
        quality_rank=6,
        cost_efficiency_rank=1,
        description="GPT-5.4 nano tier (previous gen).",
    ),
    ModelInfo(
        id="gpt-5.2",
        context_window=400_000,
        max_output=128_000,
        input_price=1.75,
        output_price=14.0,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="advanced",
        latency_tier="medium",
        max_rpm=800,
        max_tpm=2_500_000,
        knowledge_cutoff="2025-06",
        recommended_tasks=("coding", "analysis", "agent pipelines", "data transformation"),
        fallback_models=("gpt-5.1", "gpt-5-mini"),
        quality_rank=2,
        cost_efficiency_rank=5,
        description="GPT-5.2 (previous gen).",
    ),
    ModelInfo(
        id="gpt-5.1",
        context_window=400_000,
        max_output=128_000,
        input_price=1.25,
        output_price=10.0,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="advanced",
        latency_tier="medium",
        max_rpm=1_000,
        max_tpm=3_000_000,
        knowledge_cutoff="2025-03",
        recommended_tasks=("general chat", "workflow automation", "text processing"),
        fallback_models=("gpt-5-mini", "gpt-4.1-mini"),
        quality_rank=3,
        cost_efficiency_rank=4,
        description="GPT-5.1 (previous gen).",
    ),
    ModelInfo(
        id="gpt-5-mini",
        context_window=400_000,
        max_output=64_000,
        input_price=0.25,
        output_price=2.0,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="efficient",
        latency_tier="fast",
        max_rpm=5_000,
        max_tpm=8_000_000,
        knowledge_cutoff="2025-03",
        recommended_tasks=("classification", "intent detection", "routing", "cheap chat inference"),
        fallback_models=("gpt-4.1-mini", "gpt-4.1-nano"),
        quality_rank=5,
        cost_efficiency_rank=1,
        description="GPT-5 mini (previous gen).",
    ),
    # ── Legacy ────────────────────────────────────────────────────────────────
    ModelInfo(
        id="gpt-4.1",
        context_window=1_000_000,
        max_output=65_536,
        input_price=3.0,
        output_price=12.0,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="advanced",
        latency_tier="medium",
        max_rpm=800,
        max_tpm=2_500_000,
        knowledge_cutoff="2024-12",
        recommended_tasks=("long document analysis", "legal text analysis", "large context summarization"),
        fallback_models=("gpt-4.1-mini",),
        quality_rank=4,
        cost_efficiency_rank=7,
        description="GPT-4.1 (legacy).",
    ),
    ModelInfo(
        id="gpt-4.1-mini",
        context_window=1_000_000,
        max_output=32_768,
        input_price=0.80,
        output_price=3.20,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="efficient",
        latency_tier="fast",
        max_rpm=4_000,
        max_tpm=6_000_000,
        knowledge_cutoff="2024-12",
        recommended_tasks=("chatbots", "summarization", "customer support"),
        fallback_models=("gpt-4.1-nano",),
        quality_rank=6,
        cost_efficiency_rank=2,
        description="GPT-4.1 mini (legacy).",
    ),
    ModelInfo(
        id="gpt-4.1-nano",
        context_window=1_000_000,
        max_output=16_384,
        input_price=0.20,
        output_price=0.80,
        supports_tools=True,
        supports_vision=False,
        supports_streaming=True,
        supports_json_mode=True,
        capability_tier="lightweight",
        latency_tier="very_fast",
        max_rpm=8_000,
        max_tpm=12_000_000,
        knowledge_cutoff="2024-12",
        recommended_tasks=("intent detection", "classification", "LLM router"),
        fallback_models=(),
        quality_rank=7,
        cost_efficiency_rank=3,
        description="GPT-4.1 nano (legacy).",
    ),
    ModelInfo(
        id="gpt-5-nano",
        context_window=400_000,
        max_output=32_768,
        input_price=0.05,
        output_price=0.40,
        capability_tier="lightweight",
        latency_tier="very_fast",
        description="GPT-5 nano (legacy).",
    ),
    ModelInfo(
        id="gpt-5.2-pro",
        context_window=1_050_000,
        max_output=128_000,
        input_price=21.0,
        output_price=168.0,
        capability_tier="frontier",
        latency_tier="slow",
        description="GPT-5.2 with maximum compute (legacy premium).",
    ),
    ModelInfo(
        id="gpt-5-pro",
        context_window=1_050_000,
        max_output=128_000,
        input_price=15.0,
        output_price=120.0,
        capability_tier="frontier",
        latency_tier="slow",
        description="GPT-5 with maximum compute (legacy premium).",
    ),
    ModelInfo(
        id="gpt-4o",
        context_window=128_000,
        max_output=16_384,
        input_price=2.50,
        output_price=10.0,
        description="GPT-4o (legacy).",
    ),
    ModelInfo(
        id="gpt-4o-mini",
        context_window=128_000,
        max_output=16_384,
        input_price=0.15,
        output_price=0.60,
        description="GPT-4o mini (legacy).",
    ),
    ModelInfo(
        id="o3",
        context_window=200_000,
        max_output=100_000,
        input_price=2.0,
        output_price=8.0,
        description="o3 reasoning (legacy).",
    ),
    ModelInfo(
        id="o3-pro",
        context_window=200_000,
        max_output=100_000,
        input_price=20.0,
        output_price=80.0,
        description="o3 with maximum compute (legacy premium).",
    ),
    ModelInfo(
        id="o3-mini",
        context_window=200_000,
        max_output=100_000,
        input_price=1.10,
        output_price=4.40,
        description="o3-mini reasoning (legacy).",
    ),
    ModelInfo(
        id="o4-mini",
        context_window=200_000,
        max_output=100_000,
        input_price=1.10,
        output_price=4.40,
        description="o4-mini reasoning (legacy).",
    ),
    ModelInfo(
        id="o1",
        context_window=200_000,
        max_output=100_000,
        input_price=15.0,
        output_price=60.0,
        description="o1 reasoning (legacy).",
    ),
    ModelInfo(
        id="o1-mini",
        context_window=200_000,
        max_output=100_000,
        input_price=1.10,
        output_price=4.40,
        description="o1-mini reasoning (legacy).",
    ),
]
