import {useEffect,useState} from 'react'
import {useProjects,type Project,type Source} from './store'
import {useSessionStore} from '../store/session'
import {useAppStore} from '../store/appStore'
import {request,type Book} from '../books/api'
import {openBookSource} from '../books/readingNavigation'
import {listNotes} from '../notes/api'
import {useNotesStore} from '../notes/store'
import {listBoards} from '../whiteboard/api'
import {listArtifacts} from '../artifacts/api'
import type {Artifact} from '../artifacts/types'
import {useFileViewerStore} from '../store/fileViewerStore'
import {StudioDialog} from '../studio/StudioDialog'
import './projects.css'

function openSource(s:Source){
 const set=useAppStore.getState().setActiveTab
 if(s.kind==='book')openBookSource(s.target)
 else if(s.kind==='note'){useNotesStore.getState().select(s.target);set('notes')}
 else if(s.kind==='whiteboard'){localStorage.setItem('yapoc-whiteboard-target',s.target);set('whiteboard')}
 else if(s.kind==='link'){if(/^https?:\/\//.test(s.target))window.open(s.target,'_blank','noopener,noreferrer')}
 else {useFileViewerStore.getState().selectFile({path:s.target,name:s.label});set('artifacts')}
}
export function ProjectsTab({active}:{active:boolean}){
 const {projects,activeId,save,remove,refresh,activate}=useProjects(),sessions=useSessionStore(s=>s.sessions)
 const [draft,setDraft]=useState<Partial<Project>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState('Overview'),[catalog,setCatalog]=useState<Source[]>([]),[artifacts,setArtifacts]=useState<Artifact[]>([]),[link,setLink]=useState(''),[target,setTarget]=useState(''),[kind,setKind]=useState<Source['kind']>('link'),[deleting,setDeleting]=useState(false)
 const project=projects.find(p=>p.id===activeId)
 useEffect(()=>{if(!active)return;let cancelled=false;void refresh().catch(e=>{if(!cancelled)setError(e.message)});void Promise.allSettled([request<Book[]>(),listNotes(),listBoards(),listArtifacts()]).then(([b,n,w,a])=>{if(cancelled)return;const options:Source[]=[];if(b.status==='fulfilled')options.push(...b.value.map(x=>({kind:'book' as const,target:x.id,label:x.title,always:false})));if(n.status==='fulfilled')options.push(...n.value.notes.map(x=>({kind:'note' as const,target:x.id,label:x.title,always:false})));if(w.status==='fulfilled')options.push(...w.value.map(x=>({kind:'whiteboard' as const,target:x.id,label:x.name,always:false})));if(a.status==='fulfilled'){setArtifacts(a.value);options.push(...a.value.map(x=>({kind:'artifact' as const,target:x.path,label:x.name,always:false})))}setCatalog(options);if([b,n,w,a].some(r=>r.status==='rejected'))setError('Some sources could not be loaded. Refresh to try again.')});return()=>{cancelled=true}},[active,refresh])
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function update(patch:Partial<Project>){if(project)await save({...project,...patch})}
 const linked=sessions.filter(s=>project?.sessions.includes(s.id)),results=artifacts.filter(a=>a.source_session&&project?.sessions.includes(a.source_session))
 return <section className="projects-tab"><header><div><small>CONNECTED WORK</small><h1>{project?.name||'Projects'}</h1><p>{project?.description||'Bring your reading, designs and conversations together.'}</p></div><div><button onClick={()=>{useProjects.setState({activeId:null});setSection('Overview')}}>All projects</button><button onClick={()=>setDraft({name:'',description:'',brief:'',sources:[],sessions:[]})}>New project</button><button disabled={busy} onClick={()=>void action(refresh)}>Refresh</button></div></header>{error&&<p role="alert">{error}</p>}
 {!project?<div className="project-grid">{projects.map(p=><article key={p.id}><h2>{p.name}</h2><p>{p.description||'A new workspace'}</p><small>{p.sources.length} sources · {p.sessions.length} conversations · {new Date(p.updated_at).toLocaleDateString()}</small><button onClick={()=>{useProjects.setState({activeId:p.id});setSection('Overview')}}>Open project</button><button onClick={()=>activate(p)}>Continue</button></article>)}{!projects.length&&<p>Create a project, then link existing books, notes, diagrams or files.</p>}</div>:<>
 <nav aria-label="Project views">{['Overview','Sources','Conversations','Results'].map(v=><button aria-pressed={section===v} key={v} onClick={()=>setSection(v)}>{v}</button>)}<button onClick={()=>activate(project)}>Continue workspace ↗</button></nav>
 {section==='Overview'&&<div className="project-grid"><article><h2>Project brief</h2><p className="project-brief">{project.brief||'Describe the objective, constraints and preferences agents should understand.'}</p><button onClick={()=>setDraft(project)}>Edit brief and details</button></article><article><h2>Your workspace</h2><p>{project.sources.length} linked sources · {linked.length} local conversations · {results.length} results</p><p>Use the Workspace selector to pair Books + Notes, Whiteboard + Chat, or Artifacts + Chat.</p><button disabled={busy} onClick={()=>void action(async()=>{useSessionStore.getState().newSession();const id=useSessionStore.getState().activeId!;await update({sessions:[...project.sessions,id]});useAppStore.getState().setActiveTab('chat')})}>New project conversation</button></article><article><h2>Project settings</h2><p>Linked resources can belong to multiple projects.</p><button onClick={()=>setDeleting(true)}>Delete project…</button></article></div>}
 {section==='Sources'&&<><h2>Linked sources</h2><p>Only notes marked “Always include” add excerpts to every message. Other sources are references agents can inspect when needed.</p><div className="project-sources">{project.sources.map((s,i)=><article key={`${s.kind}:${s.target}`}><div><small>{s.kind}</small><button onClick={()=>openSource(s)}>{s.label} ↗</button><small>{s.target}</small></div>{s.kind==='note'&&<label><input type="checkbox" checked={s.always} disabled={busy} onChange={()=>void action(()=>update({sources:project.sources.map((x,j)=>j===i?{...x,always:!x.always}:x)}))}/>Always include</label>}<button disabled={busy} onClick={()=>void action(()=>update({sources:project.sources.filter((_,j)=>j!==i)}))}>Unlink</button></article>)}</div><h3>Add from your library</h3><select aria-label="Link existing source" value="" disabled={busy} onChange={e=>{const source=catalog[Number(e.target.value)];if(source)void action(()=>update({sources:[...project.sources,source]}))}}><option value="">Choose a book, note, canvas or artifact…</option>{catalog.map((s,i)=>!project.sources.some(x=>x.kind===s.kind&&x.target===s.target)&&<option key={i} value={i}>{s.kind} · {s.label}</option>)}</select><form onSubmit={e=>{e.preventDefault();void action(async()=>{await update({sources:[...project.sources,{kind,target,label:link,always:false}]});setLink('');setTarget('')})}}><h3>Add a link or workspace file</h3><select aria-label="Source type" value={kind} onChange={e=>setKind(e.target.value as Source['kind'])}><option value="link">Web link</option><option value="file">Workspace file</option></select><input aria-label="Source label" placeholder="Label" required maxLength={200} value={link} onChange={e=>setLink(e.target.value)}/><input aria-label="Source target" placeholder={kind==='link'?'https://…':'Relative workspace path'} type={kind==='link'?'url':'text'} required maxLength={1000} value={target} onChange={e=>setTarget(e.target.value)}/><button disabled={busy}>Link source</button></form></>}
 {section==='Conversations'&&<><h2>Project conversations</h2>{linked.map(s=><article key={s.id}><button onClick={()=>{useSessionStore.getState().loadSession(s.id);useAppStore.getState().setActiveTab('chat')}}>{s.name}</button><button disabled={busy} onClick={()=>void action(()=>update({sessions:project.sessions.filter(id=>id!==s.id)}))}>Unlink</button></article>)}<select aria-label="Link conversation" value="" disabled={busy} onChange={e=>void action(()=>update({sessions:[...project.sessions,e.target.value]}))}><option value="">Link an existing conversation…</option>{sessions.filter(s=>!projects.some(p=>p.sessions.includes(s.id))).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><p>Conversation history remains in its existing storage. A conversation belongs to one project.</p></>}
 {section==='Results'&&<><h2>Results from project conversations</h2>{!results.length&&<p>No artifacts linked to these conversations yet.</p>}{results.map(a=><article key={a.id}><button onClick={()=>openSource({kind:'artifact',target:a.path,label:a.name,always:false})}>{a.name} ↗</button><small>{a.source_agent} · {new Date(a.updated_at).toLocaleString()}</small></article>)}</>}
 </>}
 {draft&&<StudioDialog label="Edit project" onClose={()=>!busy&&setDraft(null)}><form className="project-editor" onSubmit={e=>{e.preventDefault();void action(async()=>{const p=await save(draft);useProjects.setState({activeId:p.id});setDraft(null)})}}><h2>{draft.id?'Edit project':'Create project'}</h2><label>Name<input required maxLength={120} value={draft.name||''} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Description<input maxLength={1000} value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Brief<textarea rows={8} maxLength={8000} value={draft.brief||''} onChange={e=>setDraft({...draft,brief:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy}>Save project</button><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button></form></StudioDialog>}
 {deleting&&project&&<StudioDialog label="Delete project" onClose={()=>setDeleting(false)}><div className="project-editor"><h2>Delete {project.name}?</h2><p>Books, notes, canvases, files and conversations will be kept.</p><button disabled={busy} onClick={()=>void action(async()=>{await remove(project);setDeleting(false)})}>Delete project</button><button onClick={()=>setDeleting(false)}>Cancel</button>{error&&<p role="alert">{error}</p>}</div></StudioDialog>}
 </section>
}
