import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from 'react'
import { Box, Braces, CircleUserRound, Cloud, Database, Download, FileBox, FileText, GitBranch, Layers3, Maximize2, Network, Plus, RefreshCw, Save, Trash2, X, ZoomIn, ZoomOut } from 'lucide-react'
import { createBoard,createCard,createEdge,deleteBoard,deleteCard,deleteEdge,exportBoard,getBoard,listBoards,renameBoard,updateCard,updateEdge,type Board,type BoardCard,type BoardEdge,type CanvasInfo,type CardColor,type CardKind,type EdgeColor,type EdgeDirection,type EdgeRouting,type EdgeStyle,type Relationship } from './api'

const TYPES:Array<{kind:CardKind;label:string;icon:typeof Box;color:CardColor;group:'Architecture'|'Logic'}>=[
  {kind:'actor',label:'Actor',icon:CircleUserRound,color:'violet',group:'Architecture'},{kind:'component',label:'Component',icon:Box,color:'blue',group:'Architecture'},
  {kind:'service',label:'Service',icon:Cloud,color:'mint',group:'Architecture'},{kind:'api',label:'API',icon:Braces,color:'blue',group:'Architecture'},
  {kind:'database',label:'Database',icon:Database,color:'amber',group:'Architecture'},{kind:'queue',label:'Queue',icon:Layers3,color:'violet',group:'Architecture'},
  {kind:'event',label:'Event',icon:Network,color:'rose',group:'Architecture'},{kind:'interface',label:'Interface',icon:Braces,color:'mint',group:'Architecture'},
  {kind:'module',label:'Module',icon:FileBox,color:'blue',group:'Architecture'},{kind:'external',label:'External',icon:Cloud,color:'rose',group:'Architecture'},
  {kind:'decision',label:'Decision',icon:GitBranch,color:'amber',group:'Architecture'},{kind:'note',label:'Note',icon:FileText,color:'amber',group:'Architecture'},
  {kind:'process',label:'Process',icon:Box,color:'blue',group:'Logic'},{kind:'condition',label:'Condition',icon:GitBranch,color:'amber',group:'Logic'},
  {kind:'terminator',label:'Start / End',icon:CircleUserRound,color:'mint',group:'Logic'},{kind:'input_output',label:'Input / Output',icon:Braces,color:'violet',group:'Logic'},
  {kind:'document',label:'Document',icon:FileText,color:'amber',group:'Logic'},{kind:'data_store',label:'Data store',icon:Database,color:'blue',group:'Logic'},
  {kind:'subprocess',label:'Subprocess',icon:Layers3,color:'mint',group:'Logic'},{kind:'manual_input',label:'Manual input',icon:FileBox,color:'rose',group:'Logic'},
  {kind:'preparation',label:'Preparation',icon:Box,color:'violet',group:'Logic'},{kind:'connector',label:'Connector',icon:Network,color:'amber',group:'Logic'},
  {kind:'delay',label:'Delay',icon:Cloud,color:'rose',group:'Logic'},
]
const RELATIONSHIPS:Relationship[]=['calls','depends_on','reads','writes','emits','subscribes','contains','implements','extends','flows_to','blocks','related']
const SHAPE_SIZES:Partial<Record<CardKind,{width:number;height:number}>>={condition:{width:180,height:180},terminator:{width:230,height:110},input_output:{width:250,height:135},document:{width:230,height:145},connector:{width:160,height:100},delay:{width:220,height:130}}
const EMPTY:Board={canvas:{id:'main',name:'System design',description:'',created_by:'system',created_at:'',updated_at:''},revision:0,updated_at:null,cards:[],edges:[]}
const label=(value:string)=>value.replace(/_/g,' ')

function parseDetails(text:string):Record<string,string>{const out:Record<string,string>={};for(const line of text.split('\n')){const at=line.indexOf(':');if(at>0)out[line.slice(0,at).trim()]=line.slice(at+1).trim()}return out}
function detailsText(details:Record<string,unknown>){return Object.entries(details||{}).map(([k,v])=>`${k}: ${typeof v==='string'?v:JSON.stringify(v)}`).join('\n')}

function edgeGeometry(a:BoardCard,b:BoardCard,routing:EdgeRouting){
  const ac={x:a.x+a.width/2,y:a.y+a.height/2},bc={x:b.x+b.width/2,y:b.y+b.height/2},dx=bc.x-ac.x,dy=bc.y-ac.y
  const exit=(w:number,h:number)=>1/Math.max(Math.abs(dx)/(w/2),Math.abs(dy)/(h/2),.001)
  const sa=exit(a.width,a.height),sb=exit(b.width,b.height)
  const start={x:ac.x+dx*sa,y:ac.y+dy*sa},end={x:bc.x-dx*sb,y:bc.y-dy*sb},middle={x:(start.x+end.x)/2,y:(start.y+end.y)/2}
  if(routing==='orthogonal')return{d:`M ${start.x} ${start.y} L ${middle.x} ${start.y} L ${middle.x} ${end.y} L ${end.x} ${end.y}`,label:middle}
  if(routing==='curved'){const length=Math.hypot(dx,dy)||1,curve={x:middle.x-dy/length*55,y:middle.y+dx/length*55};return{d:`M ${start.x} ${start.y} Q ${curve.x} ${curve.y} ${end.x} ${end.y}`,label:curve}}
  return{d:`M ${start.x} ${start.y} L ${end.x} ${end.y}`,label:middle}
}

function CardEditor({card,kind,position,boardId,onClose,onSave}:{card?:BoardCard;kind?:CardKind;position?:{x:number;y:number};boardId:string;onClose:()=>void;onSave:(value:Partial<BoardCard>&Pick<BoardCard,'title'>)=>Promise<void>}){
  const preset=TYPES.find(x=>x.kind===(card?.kind||kind));const [title,setTitle]=useState(card?.title||'');const [body,setBody]=useState(card?.body||'');const [type,setType]=useState<CardKind>(card?.kind||kind||'component');const [color,setColor]=useState<CardColor>(card?.color||preset?.color||'blue');const [details,setDetails]=useState(detailsText(card?.details||{}));const [busy,setBusy]=useState(false)
  return <div className="whiteboard-modal" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="whiteboard-editor" onSubmit={async e=>{e.preventDefault();setBusy(true);const shapeSize=SHAPE_SIZES[type];try{await onSave({title,body,kind:type,color,details:parseDetails(details),board_id:boardId,x:position?.x??card?.x??100,y:position?.y??card?.y??100,...(!card&&shapeSize?shapeSize:{})});onClose()}finally{setBusy(false)}}}>
    <header><div><strong>{card?'Edit design node':'Add design node'}</strong><span>Agents receive the type, description, and structured details.</span></div><button type="button" onClick={onClose}><X size={16}/></button></header>
    <div className="wb-type-picker">{TYPES.map(({kind:k,label:l,icon:Icon,color:c})=><button type="button" key={k} aria-pressed={type===k} onClick={()=>{setType(k);if(!card)setColor(c)}}><Icon size={14}/><span>{l}</span></button>)}</div>
    <label>Name<input autoFocus required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Authentication service"/></label>
    <label>Purpose and behavior<textarea rows={4} maxLength={4000} value={body} onChange={e=>setBody(e.target.value)} placeholder="What it owns, guarantees, and must not do…"/></label>
    <label>Structured details <small>one key: value per line</small><textarea rows={4} value={details} onChange={e=>setDetails(e.target.value)} placeholder={'technology: FastAPI\nendpoint: POST /sessions\nSLO: p95 under 200 ms'}/></label>
    <div className="whiteboard-editor-row"><fieldset><legend>Color</legend><div>{(['amber','mint','blue','rose','violet'] as CardColor[]).map(x=><button key={x} type="button" className={`board-color is-${x}`} aria-label={x} aria-pressed={color===x} onClick={()=>setColor(x)}/>)}</div></fieldset></div>
    <footer><button type="button" onClick={onClose}>Cancel</button><button className="is-primary" disabled={busy||!title.trim()}>{busy?'Saving…':'Save node'}</button></footer>
  </form></div>
}

function EdgeEditor({edge,onClose,onSaved,onDelete}:{edge:BoardEdge;onClose:()=>void;onSaved:(edge:BoardEdge)=>void;onDelete:()=>Promise<void>}){
  const[relationship,setRelationship]=useState(edge.relationship);const[labelText,setLabelText]=useState(edge.label);const[style,setStyle]=useState(edge.style);const[direction,setDirection]=useState(edge.direction);const[routing,setRouting]=useState(edge.routing);const[color,setColor]=useState(edge.color);const[thickness,setThickness]=useState(edge.thickness);const[busy,setBusy]=useState(false)
  return <div className="whiteboard-modal"><form className="whiteboard-editor wb-edge-editor" onSubmit={async e=>{e.preventDefault();setBusy(true);try{onSaved(await updateEdge(edge,{relationship,label:labelText,style,direction,routing,color,thickness}));onClose()}finally{setBusy(false)}}}>
    <header><div><strong>Configure connection</strong><span>Direction and visual style are preserved for agents and exports.</span></div><button type="button" onClick={onClose}><X size={16}/></button></header>
    <div className="wb-edge-editor-grid"><label>Relationship<select value={relationship} onChange={e=>setRelationship(e.target.value as Relationship)}>{RELATIONSHIPS.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Direction<select value={direction} onChange={e=>setDirection(e.target.value as EdgeDirection)}><option value="forward">Forward →</option><option value="backward">Backward ←</option><option value="both">Both ↔</option><option value="none">Undirected —</option></select></label><label>Route<select value={routing} onChange={e=>setRouting(e.target.value as EdgeRouting)}><option value="straight">Straight</option><option value="curved">Curved</option><option value="orthogonal">Right angles</option></select></label><label>Line<select value={style} onChange={e=>setStyle(e.target.value as EdgeStyle)}><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option></select></label></div>
    <label>Label<input maxLength={80} value={labelText} onChange={e=>setLabelText(e.target.value)} placeholder={label(relationship)}/></label>
    <div className="whiteboard-editor-row"><fieldset><legend>Color</legend><div>{(['default','amber','mint','blue','rose','violet'] as EdgeColor[]).map(x=><button key={x} type="button" className={`wb-edge-color is-${x}`} aria-label={x} aria-pressed={color===x} onClick={()=>setColor(x)}/>)}</div></fieldset><label>Thickness <strong>{thickness}px</strong><input type="range" min="1" max="6" step="1" value={thickness} onChange={e=>setThickness(Number(e.target.value))}/></label></div>
    <footer><button type="button" className="is-danger" onClick={async()=>{await onDelete();onClose()}}>Delete connection</button><button type="button" onClick={onClose}>Cancel</button><button className="is-primary" disabled={busy}>{busy?'Saving…':'Save connection'}</button></footer>
  </form></div>
}

function CanvasDialog({canvas,onClose,onSaved,onDelete}:{canvas?:CanvasInfo;onClose:()=>void;onSaved:(canvas:CanvasInfo)=>void;onDelete?:()=>Promise<void>}){const[name,setName]=useState(canvas?.name||'');const[description,setDescription]=useState(canvas?.description||'');const[confirm,setConfirm]=useState(false);return <div className="whiteboard-modal"><form className="whiteboard-editor wb-small-dialog" onSubmit={async e=>{e.preventDefault();const saved=canvas?await renameBoard(canvas.id,name,description):await createBoard(name,description);onSaved(saved);onClose()}}><header><strong>{canvas?'Canvas settings':'New design canvas'}</strong><button type="button" onClick={onClose}><X size={16}/></button></header><label>Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Payments architecture"/></label><label>Design intent<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What this design explains and its constraints"/></label><footer>{onDelete&&<button type="button" className="is-danger" onClick={async()=>{if(!confirm){setConfirm(true);return}await onDelete();onClose()}}>{confirm?'Confirm delete':'Delete canvas'}</button>}<button type="button" onClick={onClose}>Cancel</button><button className="is-primary">{canvas?'Save':'Create canvas'}</button></footer></form></div>}

function ExportDialog({board,onClose}:{board:Board;onClose:()=>void}){const[format,setFormat]=useState<'markdown'|'mermaid'|'json'>('markdown');const[busy,setBusy]=useState('');const[result,setResult]=useState('');const run=async(destination:'download'|'notes'|'workspace'|'artifact',requestedFormat=format)=>{setBusy(destination);try{const r=await exportBoard(board.canvas.id,requestedFormat,destination);if(destination==='download'&&r.content){const url=URL.createObjectURL(new Blob([r.content],{type:r.mime}));const a=document.createElement('a');a.href=url;a.download=r.filename||'design';a.click();URL.revokeObjectURL(url);setResult(`Downloaded ${r.filename}`)}else setResult(r.reference||r.path||'Exported')}catch(e){setResult(e instanceof Error?e.message:'Export failed')}finally{setBusy('')}};return <div className="whiteboard-modal"><div className="whiteboard-editor wb-export"><header><div><strong>Export design</strong><span>Portable source plus YAPOC destinations</span></div><button onClick={onClose}><X size={16}/></button></header><label>Format<select value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="markdown">Markdown document + Mermaid</option><option value="mermaid">Mermaid diagram</option><option value="json">Structured YAPOC JSON</option></select></label><div className="wb-export-targets"><button onClick={()=>void run('download')}><Download/>Download<small>Save to this device</small></button><button onClick={()=>{setFormat('markdown');void run('notes','markdown')}}><FileText/>@notes<small>Create a reference note</small></button><button onClick={()=>void run('workspace')}><Save/>Workspace<small>app/projects/designs</small></button><button onClick={()=>void run('artifact')}><FileBox/>Artifacts<small>Versioned generated file</small></button></div>{busy&&<p>Exporting to {busy}…</p>}{result&&<p className="wb-export-result">{result}</p>}</div></div>}

export function WhiteboardTab({active}:{active:boolean}){
  const[boards,setBoards]=useState<CanvasInfo[]>([]);const[boardId,setBoardId]=useState(()=>localStorage.getItem('yapoc-whiteboard')||'main');const[board,setBoard]=useState<Board>(EMPTY);const[error,setError]=useState('');const[editor,setEditor]=useState<{card?:BoardCard;kind?:CardKind;position?:{x:number;y:number}}|null>(null);const[edgeEditor,setEdgeEditor]=useState<BoardEdge|null>(null);const[canvasDialog,setCanvasDialog]=useState<'new'|'edit'|null>(null);const[exportOpen,setExportOpen]=useState(false);const[connecting,setConnecting]=useState<{source:string;relationship:Relationship;style:EdgeStyle;direction:EdgeDirection;routing:EdgeRouting}|null>(null);const[relationship,setRelationship]=useState<Relationship>('calls');const[edgeStyle,setEdgeStyle]=useState<EdgeStyle>('solid');const[edgeDirection,setEdgeDirection]=useState<EdgeDirection>('forward');const[edgeRouting,setEdgeRouting]=useState<EdgeRouting>('straight');const[confirmDelete,setConfirmDelete]=useState<string|null>(null);const[zoom,setZoom]=useState(1);const viewport=useRef<HTMLDivElement>(null);const dragging=useRef<{id:string;dx:number;dy:number;original:BoardCard}|null>(null)
  const loadBoards=useCallback(async()=>{const items=await listBoards();setBoards(items);if(!items.some(x=>x.id===boardId)){setBoardId('main');localStorage.setItem('yapoc-whiteboard','main')}},[boardId])
  const refresh=useCallback(async(quiet=false)=>{try{const next=await getBoard(boardId);if(!dragging.current)setBoard(current=>next.revision>=current.revision||current.canvas.id!==next.canvas.id?next:current);setError('')}catch(e){if(!quiet)setError(e instanceof Error?e.message:'Canvas unavailable')}},[boardId])
  useEffect(()=>{if(!active)return;void loadBoards();void refresh();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void refresh(true)},4000);return()=>window.clearInterval(timer)},[active,loadBoards,refresh])
  const selectBoard=(id:string)=>{setBoardId(id);localStorage.setItem('yapoc-whiteboard',id);setBoard({...EMPTY,canvas:{...EMPTY.canvas,id}});setConnecting(null)}
  const saveEditor=async(value:Partial<BoardCard>&Pick<BoardCard,'title'>)=>{if(editor?.card){const saved=await updateCard(editor.card,value);setBoard(b=>({...b,cards:b.cards.map(c=>c.id===saved.id?saved:c)}))}else{const saved=await createCard(value);setBoard(b=>({...b,cards:[...b.cards,saved]}))}await refresh(true)}
  const chooseCard=async(card:BoardCard)=>{if(!connecting){setEditor({card});return}if(connecting.source===card.id){setConnecting(null);return}try{await createEdge({board_id:boardId,source_id:connecting.source,target_id:card.id,relationship:connecting.relationship,style:connecting.style,direction:connecting.direction,routing:connecting.routing,color:'default',thickness:2,label:''});setConnecting(null);await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to connect nodes')}}
  const startDrag=(e:React.PointerEvent,card:BoardCard)=>{if((e.target as HTMLElement).closest('button,a'))return;const rect=viewport.current?.getBoundingClientRect();if(!rect)return;dragging.current={id:card.id,dx:(e.clientX-rect.left+(viewport.current?.scrollLeft||0))/zoom-card.x,dy:(e.clientY-rect.top+(viewport.current?.scrollTop||0))/zoom-card.y,original:card};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
  const moveDrag=(e:React.PointerEvent)=>{const d=dragging.current,r=viewport.current?.getBoundingClientRect();if(!d||!r)return;const x=Math.max(8,Math.min(3600,(e.clientX-r.left+(viewport.current?.scrollLeft||0))/zoom-d.dx)),y=Math.max(8,Math.min(2200,(e.clientY-r.top+(viewport.current?.scrollTop||0))/zoom-d.dy));setBoard(b=>({...b,cards:b.cards.map(c=>c.id===d.id?{...c,x,y}:c)}))}
  const endDrag=async()=>{const d=dragging.current;if(!d)return;const moved=board.cards.find(c=>c.id===d.id);dragging.current=null;if(!moved||(moved.x===d.original.x&&moved.y===d.original.y))return;try{const saved=await updateCard(d.original,{x:moved.x,y:moved.y});setBoard(b=>({...b,cards:b.cards.map(c=>c.id===saved.id?saved:c)}))}catch(e){setError(e instanceof Error?e.message:'Unable to move node');await refresh(true)}}
  const add=(kind:CardKind)=>{const el=viewport.current;setEditor({kind,position:{x:((el?.scrollLeft||0)+(el?.clientWidth||800)/2)/zoom-115,y:((el?.scrollTop||0)+(el?.clientHeight||500)/2)/zoom-80}})}
  const cardMap=useMemo(()=>new Map(board.cards.map(c=>[c.id,c])),[board.cards]);const savedAge=board.updated_at?Math.max(0,Math.round((Date.now()-Date.parse(board.updated_at))/1000)):0
  return <section className="whiteboard-tab wb-designer">
    <header className="whiteboard-header wb-designer-header"><div className="wb-canvas-title"><select value={boardId} onChange={e=>selectBoard(e.target.value)}>{boards.map(x=><option key={x.id} value={x.id}>{x.name} · {x.card_count??0}</option>)}</select><button onClick={()=>setCanvasDialog('edit')} title="Canvas settings">{board.canvas.name}</button><p>{board.canvas.description||'Describe a system visually, then let agents build from it.'}</p></div><div className="wb-save-state"><span/><strong>Saved</strong>{savedAge<60?` ${savedAge}s ago`:''}</div><button onClick={()=>setCanvasDialog('new')}><Plus size={14}/>Canvas</button><button onClick={()=>setExportOpen(true)}><Download size={14}/>Export</button><button onClick={()=>void refresh()}><RefreshCw size={14}/></button></header>
    {error&&<div className="whiteboard-error">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
    <div className="wb-designer-body"><aside className="wb-node-library">{(['Architecture','Logic'] as const).map(group=><div className="wb-library-group" key={group}><strong>{group}</strong><p>{group==='Logic'?'Flowchart shapes':'System nodes'}</p>{TYPES.filter(x=>x.group===group).map(({kind,label:txt,icon:Icon})=><button key={kind} onClick={()=>add(kind)}><Icon size={15}/><span>{txt}</span><Plus size={11}/></button>)}</div>)}<div className="wb-library-tip"><strong>@whiteboard</strong><span>Reference this design from chat. Agents read its full schema.</span></div></aside>
      <div className="wb-stage"><div className="wb-canvas-toolbar"><div><button onClick={()=>setZoom(z=>Math.max(.4,z-.1))}><ZoomOut size={14}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.6,z+.1))}><ZoomIn size={14}/></button><button onClick={()=>setZoom(.65)} title="Fit design"><Maximize2 size={14}/></button></div><label>Relationship<select value={relationship} onChange={e=>setRelationship(e.target.value as Relationship)}>{RELATIONSHIPS.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Direction<select value={edgeDirection} onChange={e=>setEdgeDirection(e.target.value as EdgeDirection)}><option value="forward">→</option><option value="backward">←</option><option value="both">↔</option><option value="none">—</option></select></label><label>Route<select value={edgeRouting} onChange={e=>setEdgeRouting(e.target.value as EdgeRouting)}><option value="straight">Straight</option><option value="curved">Curved</option><option value="orthogonal">Angles</option></select></label><label>Line<select value={edgeStyle} onChange={e=>setEdgeStyle(e.target.value as EdgeStyle)}><option>solid</option><option>dashed</option><option>dotted</option></select></label></div>
      {connecting&&<div className="whiteboard-connect-banner"><GitBranch size={14}/>Select a target for <strong>{label(connecting.relationship)}</strong><button onClick={()=>setConnecting(null)}>Cancel</button></div>}
      <div className="whiteboard-viewport" ref={viewport} onDoubleClick={e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();setEditor({kind:'component',position:{x:(e.clientX-r.left+e.currentTarget.scrollLeft)/zoom,y:(e.clientY-r.top+e.currentTarget.scrollTop)/zoom}})}}><div className="whiteboard-canvas" style={{transform:`scale(${zoom})`}}>
        <svg className="whiteboard-edges">{board.edges.map(edge=>{const a=cardMap.get(edge.source_id),b=cardMap.get(edge.target_id);if(!a||!b)return null;const geometry=edgeGeometry(a,b,edge.routing||'straight');const edgeColor=edge.color||'default';const customStyle={"--edge-width":`${edge.thickness||2}px`} as CSSProperties;return <g key={edge.id} className={`is-${edge.style} edge-${edgeColor}`} style={customStyle}><defs><marker id={`arrow-${edge.id}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs><path d={geometry.d} markerStart={edge.direction==='backward'||edge.direction==='both'?`url(#arrow-${edge.id})`:undefined} markerEnd={edge.direction==='forward'||edge.direction==='both'?`url(#arrow-${edge.id})`:undefined}/></g>})}</svg>
        {board.edges.map(edge=>{const a=cardMap.get(edge.source_id),b=cardMap.get(edge.target_id);if(!a||!b)return null;const geometry=edgeGeometry(a,b,edge.routing||'straight');const glyph={none:'—',forward:'→',backward:'←',both:'↔'}[edge.direction||'forward'];return <button key={edge.id} className={`wb-edge-label edge-${edge.color||'default'}`} style={{left:geometry.label.x,top:geometry.label.y}} onClick={()=>setEdgeEditor(edge)} title="Configure connection">{edge.label||label(edge.relationship)} {glyph}</button>})}
        {board.cards.map(card=>{const TypeIcon=TYPES.find(x=>x.kind===card.kind)?.icon||Box;return <article key={card.id} className={`board-card is-${card.color} ${connecting?.source===card.id?'is-connecting':''} kind-${card.kind}`} style={{left:card.x,top:card.y,width:card.width,height:card.height}} onPointerDown={e=>startDrag(e,card)} onPointerMove={moveDrag} onPointerUp={()=>void endDrag()} onPointerCancel={()=>void endDrag()}><header><span><TypeIcon size={12}/>{label(card.kind)}</span><div><button onClick={e=>{e.stopPropagation();setConnecting({source:card.id,relationship,style:edgeStyle,direction:edgeDirection,routing:edgeRouting})}} title="Connect node"><GitBranch size={13}/></button><button onClick={e=>{e.stopPropagation();setConfirmDelete(card.id)}}><Trash2 size={13}/></button></div></header><button className="board-card-content" onClick={()=>void chooseCard(card)}><strong>{card.title}</strong>{card.body&&<p>{card.body}</p>}{Object.keys(card.details||{}).length>0&&<dl>{Object.entries(card.details).slice(0,3).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>}</button><footer><span className="board-avatar">{card.created_by.slice(0,2).toUpperCase()}</span><span>{card.created_by}</span><time>v{card.revision}</time></footer>{confirmDelete===card.id&&<div className="board-delete-confirm"><span>Delete this node?</span><button onClick={async()=>{await deleteCard(card.id);setConfirmDelete(null);await refresh()}}>Delete</button><button onClick={()=>setConfirmDelete(null)}>Keep</button></div>}</article>})}
        {!board.cards.length&&<button className="whiteboard-empty" onClick={()=>add('component')}><Network size={27}/><strong>Design this system</strong><span>Add architecture nodes or ask an agent to generate the canvas.</span></button>}</div></div></div></div>
    {editor&&<CardEditor card={editor.card} kind={editor.kind} position={editor.position} boardId={boardId} onClose={()=>setEditor(null)} onSave={saveEditor}/>} {edgeEditor&&<EdgeEditor edge={edgeEditor} onClose={()=>setEdgeEditor(null)} onSaved={saved=>setBoard(b=>({...b,edges:b.edges.map(e=>e.id===saved.id?saved:e)}))} onDelete={async()=>{await deleteEdge(edgeEditor.id);await refresh()}}/>}{canvasDialog&&<CanvasDialog canvas={canvasDialog==='edit'?board.canvas:undefined} onClose={()=>setCanvasDialog(null)} onSaved={c=>{void loadBoards();selectBoard(c.id)}} onDelete={canvasDialog==='edit'&&boardId!=='main'?async()=>{await deleteBoard(boardId);selectBoard('main');await loadBoards()}:undefined}/>}{exportOpen&&<ExportDialog board={board} onClose={()=>setExportOpen(false)}/>} {/* dialogs */}
  </section>
}
